### ISSUE TITLE
Öğretim Görevlisi Ekran Görüntüleri Hkn.

### ISSUE THREAD

**Issue by gorkemDayi** [gorkemDayi/BBM487-20142-16#3]
Hocam bilgi gözlem sisteminde öğretim görevlilerinin kullandığı ara yüzün ekran görüntüsünü Piazzada paylaşacaktınız. Benden hatırlatmamı istemiştiniz.

**Comment by TugbaErdogan** [comment]
https://piazza.com/hacettepe.edu.tr/spring2015/bbm382bbm487/resources adresinden erişebilirsiniz
